#ifndef INCLUDED_WUI_DEFINITIONS_H
#define INCLUDED_WUI_DEFINITIONS_H

#ifndef WUI_NAME_SIZE
    #define WUI_NAME_SIZE 32
#endif

#ifndef WUI_WINDOW_INSTANCE_HASH_TABLE_CAPACITY
    #define WUI_WINDOW_INSTANCE_HASH_TABLE_CAPACITY 1024
#endif

#endif /*INCLUDED_WUI_DEFINITIONS_H*/
